# App Java ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: app
data:
  DATABASE_HOST: 192.168.59.102
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PORT: 5432
  DATABASE_PASS: mysecretpassword
