version: '3'

services:
  app:
    image: 'didis/app:1.0'
    ports:
      - "8080:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASS=mysecretpassword
    hostname: BEZA
    
  db:
    image: 'postgres'
    ports:
      - "5432:5432"      
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword